---
apiVersion: v1
kind: Namespace
metadata:
  name: youtube-apps
  labels:
    shared-gateway-access: "true"
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: youtube-internal
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: youtube-certs
spec: {}
status: {}
