---
# youtube.com/v/j321wi -> https://youtube.com/watch
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-legacy-watch
spec:
  parentRefs:
    - name: youtube-gw
      namespace: nginx
      sectionName: https
  hostnames:
    - youtube.com
  rules:
    - matches:
        - path: # match legacy version
            type: PathPrefix
            value: /v
      filters:
        - type: RequestRedirect
          requestRedirect:
            path: # replaces full path -> drops ID
              type: ReplaceFullPath
              replaceFullPath: /watch
            statusCode: 302
